---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(here)
library(snakecase)
```

## Importing new data
```{r}
# here function: tells us where we are, while telling R to go back to where the project file is located - keeping your project contained
# new_data <- read_csv(here("data/new_data.csv"))

here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )

# name_repair: updating column names while importing your data
# n_max: how many rows is loaded from this specific file
```

## Exercise: Reading other files

```{r}
# read in a few other data files
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```

## Making a function to add numbers
```{r}
#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

# {...} are used after function() to make a function body
# we don't necessarily need the return, but it can be good practice to make sure you get returned what you want
# to add roxygen comment; place cursor somewhere within your function
```

```{r}
#' Read in one nurses' stress data file.
#'
#' @param file_path Path to the data file
#'
#' @param max_rows Maximum number of rows in output
#'
#' @returns Outputs a data frame/tibble
#'
read <- function(file_path, max_rows = 100) {
  data <- file_path |>
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = max_rows
    )
  return(data)
}
# be careful not to overwrite a function. Check if a function name is taken by looking up the potential help page: ?function
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```


```{r}
# testing code exercise 16.7
# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```


